apk/urls.py
from django.conf.urls import patterns, url

from apkdissect.apk import views

urlpatterns = patterns('',
    url(r'^showclass/(?P<class_id>\d+)$', views.showclass, name='showclass'),
    url(r'^showapk/(?P<apk_id>\d+)$', views.showapk, name='showapk')
)

apkdissect/urls.py
from django.conf.urls import patterns, include, url


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'androidforensics.views.home', name='home'),
    #url(r'^apk/', include('apk.urls')),
    url(r'^$', 'apk.views.index', name='index'),
    url(r'^apk/(?P<apk_id>\d+)/classes_menu.json$', 'apk.views.classes_menu_json', name='classes_menu_json'),
    url(r'^apk/(?P<apk_id>\d+)/source.zip$', 'apk.views.classes_zip', name='classes_zip'),
    url(r'^apk/menu.json$', 'apk.views.menu_json', name='menu_json'),
    url(r'^$', 'apk.views.appindex', name='appindex'),
    url(r'^showclass/(?P<class_id>\d+)$', 'apk.views.showclass', name='showclass'),
    url(r'^showapk/(?P<apk_id>\d+)$', 'apk.views.showapk', name='showapk'),
    url(r'^dissect/(?P<apk_id>\d+)$', 'apk.views.dissect', name='dissect'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

apk/models.py
from django.db import models
from django.conf import settings

import os

from pygments import highlight
from pygments.lexers import JavaLexer
from pygments.formatters import HtmlFormatter

from analyze import get_classes, get_permissions, get_name

# Create your models here.

class Permission(models.Model):
    name = models.CharField(max_length=512)
    
    class Meta:
        ordering = ['name']
    
    def __unicode__(self):
        if len(self.name) > 45:
            return self.name[:42]+"..."
        return self.name
        
class DalvikClass(models.Model):
    name = models.CharField(max_length=512)
    apk = models.ForeignKey('APK')
    javasource = models.TextField()
    
    def __unicode__(self):
        return self.name
    
    def source_link(self):
    	return u'<a href="/showclass/%d">Source</a>' % (self.id)
    source_link.allow_tags = True
    
    def java_html(self):
    	return highlight(self.javasource, JavaLexer(), HtmlFormatter())


class APK(models.Model):
    apk = models.FileField(upload_to="apks/")
    sha256 = models.CharField(max_length=64, db_index=True)
    md5 = models.CharField(max_length=32, db_index=True)
    name = models.CharField(max_length=256, null=True)
    permissions = models.ManyToManyField(Permission)
    permissions_loaded = models.BooleanField(default=False)
    decompiled = models.BooleanField(default=False)
    
    def __unicode__(self):
        return self.sha256
        
    def _load_permissions(self):
        self.permissions.clear()
        for p in get_permissions(os.path.join(settings.MEDIA_ROOT, self.apk.name)):
            perm, created = Permission.objects.get_or_create(name=p)
            if created: perm.save()
            self.permissions.add(perm)
        self.save()
    
    def _load_classes(self):
        for c in DalvikClass.objects.filter(apk=self):
            c.delete()
        for name, source in get_classes(os.path.join(settings.MEDIA_ROOT, self.apk.name)):
            dalvikclass = DalvikClass(name=name)
            dalvikclass.javasource = source
            dalvikclass.apk = self
            dalvikclass.save()
        self.save()
 	
    def _load_name(self):
        self.name = get_name(os.path.join(settings.MEDIA_ROOT, self.apk.name))
        self.save()
        
        
        
    
class Device(models.Model):
    identifier = models.CharField(max_length=256)
    notes = models.TextField()
    
    def __unicode__(self):
        return self.identifier

class ImportBatch(models.Model):
	device = models.ForeignKey(Device)
	timestamp = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return u'%s @ %s' % (self.device, self.timestamp)
	
	def admin_apps_link(self):
		return u'<a href="/admin/apk/app/?batch__id__exact=%d">Show apps</a>' % (self.id)
	admin_apps_link.allow_tags = True

class App(models.Model):
	name = models.CharField(max_length=256)
	location = models.CharField(max_length=256)
	apk = models.ForeignKey(APK)
	batch = models.ForeignKey(ImportBatch)
	
	def __unicode__(self):
		return self.name
	
	def admin_source_link(self):
		return u'<a href="/admin/apk/dalvikclass/?apk__id__exact=%d">Show source</a>' % (self.id)
	admin_source_link.allow_tags = True
	
class File(models.Model):
	sha256 = models.CharField(max_length=64, db_index=True)
	apk = models.FileField(upload_to="apks/")
	
	def __unicode__(self):
		return u'File:%s' % (self.sha256)
		
		
		

apk/views.py
# Create your views here.

import json
from pprint import pprint
from io import BytesIO
import zipfile

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from apk.models import *

def index(request):
	apk = APK.objects.all()[0]
	return HttpResponseRedirect("/dissect/%d" % (apk.pk,))

def showclass(request, class_id):
	dc = get_object_or_404(DalvikClass, pk=class_id)
	return render(request, 'apk/source.html', {'dalvikclass': dc})

def appindex(request):
	return render(request, 'apk/apklist.html', {
		'apps': App.objects.all()
	})
	
def menu_json(request):
	obj = {	
		"name": "toolbar",
		"items": [
			{	"type": "menu", 
				"id": "menu_open",
				"caption": "Open APK",
				"img": "icon-edit",
				"items": [{
					"text": '<a href="/dissect/%d">%s</a>' % (apk.pk, apk.name),
					"img": "icon-page"
				} for apk in APK.objects.all()]
			}
		]
	}
	return HttpResponse(json.dumps(obj), content_type="application/json")

def showapk(request, apk_id):
	apk = get_object_or_404(APK, pk=apk_id)
	return render(request, 'apk/apk.html', {
		'apk': apk
	})

def classes_to_tree(tree, path, cid):
	if len(path) == 1:
		tree[path[0]] = cid
		return tree
	if tree.has_key(path[0]):
		tree[path[0]] = classes_to_tree(tree[path[0]], path[1:], cid)
	else:
		tree[path[0]] = classes_to_tree(dict(), path[1:], cid)
	return tree

def tree_to_menu(tree, parent=""):
	l = []
	for k, v in tree.iteritems():
		if type(v) == dict:
			l.append({
				"id": "classpath_"+parent+k,
				"text": k,
				"img": "icon-folder",
				"nodes": tree_to_menu(v, parent+k+"/")
			})
		else:
			l.append({
				"id": "class_%d" %(v,),
				"text": k,
				"img": "icon-page",
			})
	return l

def classes_menu_json(request, apk_id):
	apk = get_object_or_404(APK, pk=apk_id)
	tree = dict()
	for c in DalvikClass.objects.filter(apk=apk):
		tree = classes_to_tree(tree, c.name.split("/"), c.pk)
	return HttpResponse(json.dumps(tree_to_menu(tree)), content_type="application/json")
	
def classes_zip(request, apk_id):
	apk = get_object_or_404(APK, pk=apk_id)
	output = BytesIO()
	with zipfile.ZipFile(output, 'w') as myzip:
		for c in DalvikClass.objects.filter(apk=apk):
			myzip.writestr(c.name+".java", bytes(c.javasource))
		myzip.close()
	print dir(output)
	response = HttpResponse(output.getvalue(), mimetype="application/zip")
	response['Content-Disposition'] = "attachment;filename=%d_source.zip" % (apk.pk, )
	return response
	
def dissect(request, apk_id):
	apk = get_object_or_404(APK, pk=apk_id)
	return render(request, "apk/browser.html", {"apk": apk})

apk/templates/apk/apk.html
<!DOCTYPE html>
<html>
	<head>
		<title>Apk: {{apk.sha256}}</title>
	</head>
	<body>
		<table width="100%"">
			<tr width="100%">
				<td>
					<h3>Permissions</h3>
					<ul>
					{% for p in apk.permissions.all %}
						<li>{{p.name}}</li>
					{% endfor %}
					</ul>
				</td>
				<td rowspan="2" width="100%">
					<iframe id="source" src="" width="100%" height="100%">
					</iframe>
				<td>
			</tr>
			<tr>
				<td>
					<h3>Classes</h3>
					<ul>
					{% for c in apk.dalvikclass_set.all %}
						<li><a href="/showclass/{{c.pk}}" target="source">{{c.name}}</a></li>
					{% endfor %}
					</ul>
				</td>
			</tr>
		</table>
	</body>
</html>

apk/templates/apk/apklist.html
<!DOCTYPE html>
<html>
	<head>
		<title>Apk list</title>
	</head>
	<body>
		<ul>
			{% for app in apps %}
			<li><a href="/showapk/{{app.apk.pk}}">{{app.name}}</a></li>
			{% endfor %}
		</ul>
	</body>
</html>

apk/templates/apk/browser.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="http://w2ui.com/src/w2ui-1.3.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://w2ui.com/src/w2ui-1.3.min.js"></script>
</head>
<body style="margin: 0px;">
    <div id="layout" style="width: 100%; height: 900px;"></div>
</body>
<script>
$('#layout').w2layout({
    name: 'layout',
    panels: [
    	{ type: 'top', size: 30, style: 'background-color: #F5F6F7;'},
        { type: 'left', size: 300, resizable: true, style: 'background-color: #F5F6F7;'},
        { type: 'main', style: 'background-color: #F5F6F7; padding: 5px;' }
    ]
});

// Load top
$.getJSON("http://localhost:8000/apk/menu.json", function(data) {
	data.items.push({type:'break', id:'menubreak'});
	data.items.push({type:'html', id:'menutile', html:'{{apk.name}}'});
	w2ui['layout'].content('top', $().w2toolbar(data));
});


// Load left
$.getJSON("http://localhost:8000/apk/{{apk.pk}}/classes_menu.json", function(data) {
	
  	var mysidebar = {name: 'sidebar', img: null, nodes: [
		{ id: 'apk-properties', text: 'Properties', img: 'icon-folder', expanded: false, group: true, nodes: []},
		{ id: 'apk-files', text: 'Files', img: 'icon-folder', expanded: true, group: true, nodes: []},
		{ id: 'apk-classes', text: 'Classes', img: 'icon-folder', expanded: true, group: true, nodes: data}
	], 
	onClick: function (event) {
		if (event.target.indexOf("class_") == 0) {
			w2ui['layout'].load('main', '/showclass/'+event.target.slice(6));
		}
	}};
  	w2ui['layout'].content('left', $().w2sidebar(mysidebar));
});


</script>
</html>

apk/templates/apk/source.html
<!DOCTYPE html>
<html>
<head>
	<link href="http://prismjs.com/themes/prism.css" rel="stylesheet" />
	<style>
.highlight .hll { background-color: #ffffcc }
.highlight  { background: #f8f8f8; }
.highlight .c { color: #408080; font-style: italic } /* Comment */
.highlight .err { border: 1px solid #FF0000 } /* Error */
.highlight .k { color: #008000; font-weight: bold } /* Keyword */
.highlight .o { color: #666666 } /* Operator */
.highlight .cm { color: #408080; font-style: italic } /* Comment.Multiline */
.highlight .cp { color: #BC7A00 } /* Comment.Preproc */
.highlight .c1 { color: #408080; font-style: italic } /* Comment.Single */
.highlight .cs { color: #408080; font-style: italic } /* Comment.Special */
.highlight .gd { color: #A00000 } /* Generic.Deleted */
.highlight .ge { font-style: italic } /* Generic.Emph */
.highlight .gr { color: #FF0000 } /* Generic.Error */
.highlight .gh { color: #000080; font-weight: bold } /* Generic.Heading */
.highlight .gi { color: #00A000 } /* Generic.Inserted */
.highlight .go { color: #888888 } /* Generic.Output */
.highlight .gp { color: #000080; font-weight: bold } /* Generic.Prompt */
.highlight .gs { font-weight: bold } /* Generic.Strong */
.highlight .gu { color: #800080; font-weight: bold } /* Generic.Subheading */
.highlight .gt { color: #0044DD } /* Generic.Traceback */
.highlight .kc { color: #008000; font-weight: bold } /* Keyword.Constant */
.highlight .kd { color: #008000; font-weight: bold } /* Keyword.Declaration */
.highlight .kn { color: #008000; font-weight: bold } /* Keyword.Namespace */
.highlight .kp { color: #008000 } /* Keyword.Pseudo */
.highlight .kr { color: #008000; font-weight: bold } /* Keyword.Reserved */
.highlight .kt { color: #B00040 } /* Keyword.Type */
.highlight .m { color: #666666 } /* Literal.Number */
.highlight .s { color: #BA2121 } /* Literal.String */
.highlight .na { color: #7D9029 } /* Name.Attribute */
.highlight .nb { color: #008000 } /* Name.Builtin */
.highlight .nc { color: #0000FF; font-weight: bold } /* Name.Class */
.highlight .no { color: #880000 } /* Name.Constant */
.highlight .nd { color: #AA22FF } /* Name.Decorator */
.highlight .ni { color: #999999; font-weight: bold } /* Name.Entity */
.highlight .ne { color: #D2413A; font-weight: bold } /* Name.Exception */
.highlight .nf { color: #0000FF } /* Name.Function */
.highlight .nl { color: #A0A000 } /* Name.Label */
.highlight .nn { color: #0000FF; font-weight: bold } /* Name.Namespace */
.highlight .nt { color: #008000; font-weight: bold } /* Name.Tag */
.highlight .nv { color: #19177C } /* Name.Variable */
.highlight .ow { color: #AA22FF; font-weight: bold } /* Operator.Word */
.highlight .w { color: #bbbbbb } /* Text.Whitespace */
.highlight .mf { color: #666666 } /* Literal.Number.Float */
.highlight .mh { color: #666666 } /* Literal.Number.Hex */
.highlight .mi { color: #666666 } /* Literal.Number.Integer */
.highlight .mo { color: #666666 } /* Literal.Number.Oct */
.highlight .sb { color: #BA2121 } /* Literal.String.Backtick */
.highlight .sc { color: #BA2121 } /* Literal.String.Char */
.highlight .sd { color: #BA2121; font-style: italic } /* Literal.String.Doc */
.highlight .s2 { color: #BA2121 } /* Literal.String.Double */
.highlight .se { color: #BB6622; font-weight: bold } /* Literal.String.Escape */
.highlight .sh { color: #BA2121 } /* Literal.String.Heredoc */
.highlight .si { color: #BB6688; font-weight: bold } /* Literal.String.Interpol */
.highlight .sx { color: #008000 } /* Literal.String.Other */
.highlight .sr { color: #BB6688 } /* Literal.String.Regex */
.highlight .s1 { color: #BA2121 } /* Literal.String.Single */
.highlight .ss { color: #19177C } /* Literal.String.Symbol */
.highlight .bp { color: #008000 } /* Name.Builtin.Pseudo */
.highlight .vc { color: #19177C } /* Name.Variable.Class */
.highlight .vg { color: #19177C } /* Name.Variable.Global */
.highlight .vi { color: #19177C } /* Name.Variable.Instance */
.highlight .il { color: #666666 } /* Literal.Number.Integer.Long */
	</style>
	<title>{{dalvikclass.name}}</title>
</head>
<body>
	<script src="http://prismjs.com/prism.js"></script>
	<h1>{{dalvikclass.name}}</h1>
{{dalvikclass.java_html|safe}}
</body>
</html>